# Indexes

In [1]:
a = [1,2,3,4]
a[2]

3

In [3]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

a[1][1]

5

In [8]:
type(a)

list

# Rank , Axis and Shapes

In [4]:
# import library torch
import torch

In [6]:
t = torch.tensor(a)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# to get the shape of tensor
t.shape

torch.Size([3, 3])

In [11]:
# The rank of tensor is length of shape of tensor
len(t.shape)

2

### Reshaping tensor

In [16]:
# Reshaping canges the shape but not data inside data
print(t.reshape(1,9))
print(t.reshape(1,9).shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])


In [20]:
# tensor class
t = torch.Tensor()
type(t)

torch.Tensor

In [21]:
# Tensor attribute
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


# Creating Pytorch Tensors - Best Options

In [28]:
# Creating Options using data
import numpy as np
data = np.array([1,2,3])
data,type(data)

(array([1, 2, 3]), numpy.ndarray)

In [36]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [37]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [38]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [44]:
print(torch.get_default_dtype()) 
print(torch.tensor(np.array([1,2,3])))
print(torch.tensor(np.array([1.,2.,3.])))
print(torch.tensor(np.array([1.,2.,3.]),dtype=torch.float32))

torch.float32
tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.])


In [45]:
print(torch.eye(2))
print(torch.zeros(2,2))
print(torch.ones(2,2))
print(torch.rand(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4471, 0.6599],
        [0.7043, 0.4118]])


### Memory Sharing and Copying

In [47]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [48]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [50]:
data[0] = 0
data[1] = 0
data[2] = 0

In [51]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [52]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


# 1. Reshaping operation
# 2. Element-wise operation
# 3. Redundant operation
# 4. Access operation

### Reshaping operation

In [5]:
import torch

t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
])

In [9]:
t.shape,t.size()

(torch.Size([3, 4]), torch.Size([3, 4]))

In [10]:
# Rank of tensor
len(t.shape)

2

In [14]:
# Get the product result of shape 
print(torch.tensor(t.shape).prod())
# Get the total number of element from tensor
print(t.numel())

tensor(12)
12


In [16]:
t.reshape(4,3)

tensor([[1, 1, 1],
        [1, 2, 2],
        [2, 2, 3],
        [3, 3, 3]])

In [17]:
t.reshape(6,2)

tensor([[1, 1],
        [1, 1],
        [2, 2],
        [2, 2],
        [3, 3],
        [3, 3]])

In [18]:
t.reshape(12,1)

tensor([[1],
        [1],
        [1],
        [1],
        [2],
        [2],
        [2],
        [2],
        [3],
        [3],
        [3],
        [3]])

In [19]:
t.reshape(2,6)

tensor([[1, 1, 1, 1, 2, 2],
        [2, 2, 3, 3, 3, 3]])

In [21]:
# we can change the sha[e by squeezing and unscrewing them
t.reshape(2,2,3)

tensor([[[1, 1, 1],
         [1, 2, 2]],

        [[2, 2, 3],
         [3, 3, 3]]])

In [22]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


In [30]:
# squezzinf a tensor removes all of the axes to have a length of 1 and will be useful for changinig the rank of tensor
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])
torch.Size([12])


In [32]:
# While unsqueezing a tensor adds a dimension with a length of 1 and will use for  changing the rank of tensor
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])
torch.Size([1, 12])


# Flatten

In [33]:
# Flatten a tensor mean you are turning it into lower rank tensor than you started with
# Flattening a tensor mean we flatten a tensor we create a 1d array that contin all of the scalarcomponent of the tensor

In [45]:
# Function for flatten
def flatten(t):
    t = t.reshape(1,-1)
    t = t.squeeze()
    return t

In [46]:
flatten(t)

tensor([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [49]:
# Concatenation of tensor
t1 = torch.tensor([
    [1,2],
    [3,4]
])

t2 = torch.tensor([
    [1,2],
    [3,4]
])

In [51]:
# torch.cat((t1,t2),dim=0)

In [53]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,1,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [55]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [58]:
# Reshapin to (3,1,4,4) 1 represent for grayscale color
t = t.reshape(3,1,4,4)
t


tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 1, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [59]:
print(t.reshape(-1))
print(t.reshape(1,-1))
print(t.view(t.numel()))
print(t.flatten())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])


In [62]:
# this is actually be done in flatten of CNN because we have to maintain each image tensor differnetly so that it can preserve information
print(t.flatten(start_dim=1).shape)
print(t.flatten(start_dim=1))

torch.Size([3, 16])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


# Element-Wise tensor operation
element-wise<br>
component-wise<br>
point-wise <br>

all are same



In [63]:
import torch
import numpy as np

In [65]:
# Broadcasting

t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [68]:
t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [71]:
t1+4

tensor([[5., 6.],
        [7., 8.]])

In [72]:
t1.gt(2)
t1.lt(2)

tensor([[False, False],
        [ True,  True]])

In [75]:
t2.ge(0)
t2.le(2)

tensor([[False, False],
        [False, False]])

In [77]:
t1.abs()
t1.neg()
t1.sqrt()

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

# Redundant Operatin
A redundant operation on a tensor is an operation that reduces the number of elements contained with tensor

In [78]:
import torch
import numpy as np

In [80]:
t = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

In [81]:
print(t.sum())
print(t.numel())
print(t.sum().numel())
print(t.sum().numel() < t.numel())  

tensor(8.)
9
1
True


In [82]:
print(t.prod())
print(t.mean())
print(t.std())

tensor(0.)
tensor(0.8889)
tensor(1.1667)


In [83]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
])

In [84]:
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor([10, 10, 10, 10])
tensor([ 4,  8, 12, 16])


# Argmax
argmax tells us the index location of the maximum value inside a tensor

In [85]:
t = torch.tensor([
    [1,0,0,2],
    [3,2,1,3],
    [3,3,2,3],
    [1,2,3,5]
],dtype=torch.float32)

In [88]:
print(t.max())
print(t.argmax())
print(t.flatten())

tensor(5.)
tensor(15)
tensor([1., 0., 0., 2., 3., 2., 1., 3., 3., 3., 2., 3., 1., 2., 3., 5.])


In [91]:
# Return two tensor in which the first tensor return max value and second tensor return index location for these tesnor value for dim=0
print(t.max(dim=0))
print(t.argmax(dim=0))
# Return two tensor in which the first tensor return max value and second tensor return index location for these tesnor value for dim=1
print(t.max(dim=1))
print(t.argmax(dim=1))

torch.return_types.max(
values=tensor([3., 3., 3., 5.]),
indices=tensor([2, 2, 3, 3]))
tensor([2, 2, 3, 3])
torch.return_types.max(
values=tensor([2., 3., 3., 5.]),
indices=tensor([3, 3, 3, 3]))
tensor([3, 3, 3, 3])


In [95]:
print(t.mean(dim=0).tolist())
print(t.mean(dim=0).numpy())

[2.0, 1.75, 1.5, 3.25]
[2.   1.75 1.5  3.25]


In [96]:
print(t.mean(dim=1).tolist())
print(t.mean(dim=1).numpy())

[0.75, 2.25, 2.75, 2.75]
[0.75 2.25 2.75 2.75]
