# Indexes

In [1]:
a = [1,2,3,4]
a[2]

3

In [3]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

a[1][1]

5

In [8]:
type(a)

list

# Rank , Axis and Shapes

In [4]:
# import library torch
import torch

In [6]:
t = torch.tensor(a)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# to get the shape of tensor
t.shape

torch.Size([3, 3])

In [11]:
# The rank of tensor is length of shape of tensor
len(t.shape)

2

### Reshaping tensor

In [16]:
# Reshaping canges the shape but not data inside data
print(t.reshape(1,9))
print(t.reshape(1,9).shape)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 9])


In [20]:
# tensor class
t = torch.Tensor()
type(t)

torch.Tensor

In [21]:
# Tensor attribute
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


# Creating Pytorch Tensors - Best Options

In [28]:
# Creating Options using data
import numpy as np
data = np.array([1,2,3])
data,type(data)

(array([1, 2, 3]), numpy.ndarray)

In [36]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [37]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [38]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)

torch.float32
torch.int32
torch.int32
torch.int32


In [44]:
print(torch.get_default_dtype()) 
print(torch.tensor(np.array([1,2,3])))
print(torch.tensor(np.array([1.,2.,3.])))
print(torch.tensor(np.array([1.,2.,3.]),dtype=torch.float32))

torch.float32
tensor([1, 2, 3], dtype=torch.int32)
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.])


In [45]:
print(torch.eye(2))
print(torch.zeros(2,2))
print(torch.ones(2,2))
print(torch.rand(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4471, 0.6599],
        [0.7043, 0.4118]])


### Memory Sharing and Copying

In [47]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [48]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [50]:
data[0] = 0
data[1] = 0
data[2] = 0

In [51]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [52]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)
